---
title: "Stats and Prob final Project"
# By Andrew Kotarski and Darren Yu
output: html_document
---


```{r upload data set}
# renaming datasets
temp <- data.frame(BodyTemp)
salary <- data.frame(Employee_Salaries_2019_MDcounty)


```

```{r attaching datasets}

attach(temp)
attach(salary)

```

```{r summary statistics  Step 5}

summary(temp)
summary(salary)


```




```{r seperation by gender  Step 6} 


m_temp<-subset(temp$BodyTemp, temp$Gender=="Male")
f_temp<-subset(temp$BodyTemp, temp$Gender=="Female")

```
```{r numerical values of variances Step 7}

m_temp.var<-var(m_temp)
m_temp.var

f_temp.var<-var(f_temp)
f_temp.var

```

```{r   Fisher Test  Step 8 }

var.test(m_temp, f_temp, alternative = "two.sided")
```


```{r  histograms  Step 10}
hist(m_temp)

hist(f_temp)



```

```{r   boxplots  Step 10}
boxplot(m_temp)
boxplot(f_temp)

```

```{r QQ norm plot Male}
qqnorm(m_temp)

```

```{r QQ norm plot with qq line Male}
qqnorm(m_temp)
qqline(m_temp)
```


```{r QQ norm plot Female}
qqnorm(f_temp)

```
```{r QQ norm plot with qq line female}
qqnorm(f_temp)
qqline(f_temp)
```




```{r  Means and T test Step 12}
m_mean<-mean(m_temp)
m_mean


f_mean<-mean(f_temp)
f_mean



t.test(m_temp, f_temp)

```

