---
title: "Lab 05 - Sad plots"
author: "Group 6"
date: "03/16/2022"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 

fisheries <- readRDS(file = "data/fisheries.RDS")
staff <- read_csv(file = "data/instructional-staff.csv")

```

```{r pivot-longer}
staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))
```

```{r staff-long-plot}
staff_long %>%
  ggplot(aes(x = year, y = value, group = faculty_type, color = faculty_type)) +
  geom_line()
```

### Exercise 1


```{r staff-long-plot}
staff_long %>%
  ggplot(aes(x = year, y = value, group = faculty_type, color = faculty_type)) +
  geom_line() +
  labs(y= "Percentage of Total Staff", x = "Year", title = "Instructional Staff Employee Trends", color = "Faculty type")
```

### Exercise 2

Remove this text, and add your answer for Exercise 2 here.
Add code chunks as needed.
Don't forget to label your code chunk.
Do not use spaces in code chunk labels.

### Exercise 3

```{r}
ggplot(staff_long, aes(x = year, y = value, fill = faculty_type )) +
  geom_col(position = 'dodge') +
   labs(y= "Percentage of Total Staff", x = "Year", title = " The Proportion of Part-Time Faculty to Other", color = "Faculty type") 

```
